
# Name of the file that was downloaded from google api to enable access from python
GSHEET_SERVICE_FILE: "config_files/my-project-1472545352517-b199b7c6ff37.json"

# Name of the document where you want the logs written to
GSHEET_LOG_FILE: "Crypto Heist (Raw Data V2)"
GSHEET_LOG_FILE_START_ROW: 53776

# Name of the sheet to put all the logs
GSHEET_TAB_NAME_LOGS: "Raw_BotLogs"

# Name of the sheet to record the bot IDs
GSHEET_TAB_NAME_BOT_IDS: "Raw_BotIDs"

# Name of the sheet to record account value
GSHEET_TAB_NAME_ACCOUNT_VALUE: "Raw_AccountValue"

# Name of the main exchange that trades are made with
# EXCHANGE_ACCOUNT_NAMES: ["Ali Gateio V4", "BinanceUSAli"]
EXCHANGE_ACCOUNT_NAMES: ["My Coinbase Advanced"]

# Grouping of bots by ids to give them an easier to remember name and group similar bots.
bot_groups:
  Berlin: [1076302, 1054875, 1054872, 1054867, 1054863, 1054858, 1054856, 1054855, 1035623, 1606912]
  Nairobi: [1857805, 1857800, 1857797, 1857792, 1857774, 1857765, 1857753, 1857743, 1857448, 2760917]
  Oslo: [1042508, 1857837, 3119389, 3119403]
  Rio: [1422849, 1857831, 3119277]
  Helsinki: [2725309]
  Arturo: [3153122, 3152720]
  Raquel: [3145968]

CONVERT_SMART_TRADE:
  # After this time, convert to smart trade (seconds)
  THRESHOLD: 2592000 # 30 days
  # Convert at most this many trades at the same time.
  MAX_CONVERT: 5
