
# Name of the file that was dowloaded from google api to enable access from python
GSHEET_SERVICE_FILE: "my-project-1472545352517-b199b7c6ff37.json"

# Name of the document where you want the logs written to
GSHEET_LOG_FILE: "Crypto Heist"

# Name of the sheet to put all the logs
GSHEET_TAB_NAME: "Raw_BotLogs"

# Name of the sheet to record the bot IDs
GSHEET_TAB_NAME_BOT_IDS: "Raw_BotIDs"

# Name of the sheet to record account value
GSHEET_TAB_NAME_ACCOUNT_VALUE: "Raw_AccountValue"

# Grouping of bots by ids to give them an easier to remember name and group similar bots.
bot_groups:
  Berlin: [1035623, 1054875, 1054872, 1054867, 1054863, 1054858, 1054856, 1054855, 1076305, 1076302]
  Oslo: [1042508]