from setuptools import setup

setup(
    name='threeC',
    version='0.1',
    packages=['venv.lib.python3.7.site-packages.rsa', 'venv.lib.python3.7.site-packages.attr',
              'venv.lib.python3.7.site-packages.idna', 'venv.lib.python3.7.site-packages.pytz',
              'venv.lib.python3.7.site-packages.yaml', 'venv.lib.python3.7.site-packages.yarl',
              'venv.lib.python3.7.site-packages.py3cw', 'venv.lib.python3.7.site-packages.slack',
              'venv.lib.python3.7.site-packages.slack.rtm', 'venv.lib.python3.7.site-packages.slack.web',
              'venv.lib.python3.7.site-packages.slack.web.classes', 'venv.lib.python3.7.site-packages.slack.signature',
              'venv.lib.python3.7.site-packages.google.api', 'venv.lib.python3.7.site-packages.google.rpc',
              'venv.lib.python3.7.site-packages.google.auth', 'venv.lib.python3.7.site-packages.google.auth.crypt',
              'venv.lib.python3.7.site-packages.google.auth.transport',
              'venv.lib.python3.7.site-packages.google.auth.compute_engine',
              'venv.lib.python3.7.site-packages.google.type', 'venv.lib.python3.7.site-packages.google.oauth2',
              'venv.lib.python3.7.site-packages.google.logging.type',
              'venv.lib.python3.7.site-packages.google.api_core',
              'venv.lib.python3.7.site-packages.google.api_core.future',
              'venv.lib.python3.7.site-packages.google.api_core.gapic_v1',
              'venv.lib.python3.7.site-packages.google.api_core.operations_v1',
              'venv.lib.python3.7.site-packages.google.protobuf',
              'venv.lib.python3.7.site-packages.google.protobuf.util',
              'venv.lib.python3.7.site-packages.google.protobuf.pyext',
              'venv.lib.python3.7.site-packages.google.protobuf.compiler',
              'venv.lib.python3.7.site-packages.google.protobuf.internal',
              'venv.lib.python3.7.site-packages.google.protobuf.internal.import_test_package',
              'venv.lib.python3.7.site-packages.google.longrunning', 'venv.lib.python3.7.site-packages.pyasn1',
              'venv.lib.python3.7.site-packages.pyasn1.type', 'venv.lib.python3.7.site-packages.pyasn1.codec',
              'venv.lib.python3.7.site-packages.pyasn1.codec.ber', 'venv.lib.python3.7.site-packages.pyasn1.codec.cer',
              'venv.lib.python3.7.site-packages.pyasn1.codec.der',
              'venv.lib.python3.7.site-packages.pyasn1.codec.native', 'venv.lib.python3.7.site-packages.pyasn1.compat',
              'venv.lib.python3.7.site-packages.pyrepl', 'venv.lib.python3.7.site-packages.aiohttp',
              'venv.lib.python3.7.site-packages.certifi', 'venv.lib.python3.7.site-packages.chardet',
              'venv.lib.python3.7.site-packages.chardet.cli', 'venv.lib.python3.7.site-packages.urllib3',
              'venv.lib.python3.7.site-packages.urllib3.util', 'venv.lib.python3.7.site-packages.urllib3.contrib',
              'venv.lib.python3.7.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.urllib3.packages',
              'venv.lib.python3.7.site-packages.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.httplib2', 'venv.lib.python3.7.site-packages.oauthlib',
              'venv.lib.python3.7.site-packages.oauthlib.oauth1',
              'venv.lib.python3.7.site-packages.oauthlib.oauth1.rfc5849',
              'venv.lib.python3.7.site-packages.oauthlib.oauth1.rfc5849.endpoints',
              'venv.lib.python3.7.site-packages.oauthlib.oauth2',
              'venv.lib.python3.7.site-packages.oauthlib.oauth2.rfc6749',
              'venv.lib.python3.7.site-packages.oauthlib.oauth2.rfc6749.clients',
              'venv.lib.python3.7.site-packages.oauthlib.oauth2.rfc6749.endpoints',
              'venv.lib.python3.7.site-packages.oauthlib.oauth2.rfc6749.grant_types',
              'venv.lib.python3.7.site-packages.oauthlib.openid',
              'venv.lib.python3.7.site-packages.oauthlib.openid.connect',
              'venv.lib.python3.7.site-packages.oauthlib.openid.connect.core',
              'venv.lib.python3.7.site-packages.oauthlib.openid.connect.core.endpoints',
              'venv.lib.python3.7.site-packages.oauthlib.openid.connect.core.grant_types',
              'venv.lib.python3.7.site-packages.pygments', 'venv.lib.python3.7.site-packages.pygments.lexers',
              'venv.lib.python3.7.site-packages.pygments.styles', 'venv.lib.python3.7.site-packages.pygments.filters',
              'venv.lib.python3.7.site-packages.pygments.formatters', 'venv.lib.python3.7.site-packages.requests',
              'venv.lib.python3.7.site-packages.apiclient', 'venv.lib.python3.7.site-packages.multidict',
              'venv.lib.python3.7.site-packages.pygsheets', 'venv.lib.python3.7.site-packages.cachetools',
              'venv.lib.python3.7.site-packages.setuptools', 'venv.lib.python3.7.site-packages.setuptools.extern',
              'venv.lib.python3.7.site-packages.setuptools._vendor',
              'venv.lib.python3.7.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.7.site-packages.setuptools.command', 'venv.lib.python3.7.site-packages.uritemplate',
              'venv.lib.python3.7.site-packages.oauth2client', 'venv.lib.python3.7.site-packages.oauth2client.contrib',
              'venv.lib.python3.7.site-packages.oauth2client.contrib.django_util',
              'venv.lib.python3.7.site-packages.async_timeout', 'venv.lib.python3.7.site-packages.pkg_resources',
              'venv.lib.python3.7.site-packages.pkg_resources.extern',
              'venv.lib.python3.7.site-packages.pkg_resources._vendor',
              'venv.lib.python3.7.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python3.7.site-packages.pyasn1_modules', 'venv.lib.python3.7.site-packages.googleapiclient',
              'venv.lib.python3.7.site-packages.googleapiclient.discovery_cache',
              'venv.lib.python3.7.site-packages.requests_oauthlib',
              'venv.lib.python3.7.site-packages.requests_oauthlib.compliance_fixes',
              'venv.lib.python3.7.site-packages.google_auth_oauthlib',
              'venv.lib.python3.7.site-packages.google_auth_oauthlib.tool',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='',
    license='',
    author='ammarkothari',
    author_email='',
    description=''
)
